/**
 * 国家地区数据源
 */
export const countryList = [
    {
        regionId: 1,
        parentId: 0,
        regionName: '中国大陆',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 35,
        latitude: 105,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3974,
        parentId: 0,
        regionName: '美国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 38,
        latitude: -97,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3975,
        parentId: 0,
        regionName: '英国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 54,
        latitude: -2,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3976,
        parentId: 0,
        regionName: '法国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 46,
        latitude: 2,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3977,
        parentId: 0,
        regionName: '瑞士',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 47,
        latitude: 8,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3978,
        parentId: 0,
        regionName: '澳洲',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 0,
        latitude: 0,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3979,
        parentId: 0,
        regionName: '新西兰',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -41,
        latitude: 174,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3980,
        parentId: 0,
        regionName: '加拿大',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 60,
        latitude: -95,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3981,
        parentId: 0,
        regionName: '奥地利',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 47.3333,
        latitude: 13.3333,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3982,
        parentId: 0,
        regionName: '韩国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 37,
        latitude: 127.5,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3983,
        parentId: 0,
        regionName: '日本',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 36,
        latitude: 138,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3984,
        parentId: 0,
        regionName: '德国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 51,
        latitude: 9,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3985,
        parentId: 0,
        regionName: '意大利',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 42.8333,
        latitude: 12.8333,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3986,
        parentId: 0,
        regionName: '西班牙',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 40,
        latitude: -4,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3987,
        parentId: 0,
        regionName: '俄罗斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 60,
        latitude: 100,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3988,
        parentId: 0,
        regionName: '泰国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 15,
        latitude: 100,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3989,
        parentId: 0,
        regionName: '印度',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 20,
        latitude: 77,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3991,
        parentId: 0,
        regionName: '新加坡',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 1.3667,
        latitude: 103.8,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3992,
        parentId: 0,
        regionName: '欧洲',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 0,
        latitude: 0,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3993,
        parentId: 0,
        regionName: '北美',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 0,
        latitude: 0,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3994,
        parentId: 0,
        regionName: '南美',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 0,
        latitude: 0,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3995,
        parentId: 0,
        regionName: '亚洲',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 0,
        latitude: 0,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3996,
        parentId: 0,
        regionName: '非洲',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 0,
        latitude: 0,
        admincode: null,
        level: 1,
    },
    {
        regionId: 3997,
        parentId: 0,
        regionName: '大洋洲',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 0,
        latitude: 0,
        admincode: null,
        level: 1,
    },
    {
        regionId: 7279,
        parentId: 0,
        regionName: '朝鲜',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 127.510093,
        latitude: 40.339852,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7281,
        parentId: 0,
        regionName: '喀麦隆',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 12.354722,
        latitude: 7.369722,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7282,
        parentId: 0,
        regionName: '澳大利亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 133.775136,
        latitude: -25.274398,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7283,
        parentId: 0,
        regionName: '罗马尼亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 24.96676,
        latitude: 45.943161,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7284,
        parentId: 0,
        regionName: '荷兰',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 5.291266,
        latitude: 52.132633,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7285,
        parentId: 0,
        regionName: '马来西亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 101.975766,
        latitude: 4.210484,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7286,
        parentId: 0,
        regionName: '越南',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 108.277199,
        latitude: 14.058324,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7287,
        parentId: 0,
        regionName: '博茨瓦纳',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 24.684866,
        latitude: -22.328474,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7288,
        parentId: 0,
        regionName: '印度尼西亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 113.921327,
        latitude: -0.789275,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7289,
        parentId: 0,
        regionName: '莫桑比克',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 35.529562,
        latitude: -18.665695,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7290,
        parentId: 0,
        regionName: '芬兰',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 25.748151,
        latitude: 61.92411,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7291,
        parentId: 0,
        regionName: '菲律宾',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 121.774017,
        latitude: 12.879721,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7292,
        parentId: 0,
        regionName: '哈萨克斯坦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 66.923684,
        latitude: 48.019573,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7293,
        parentId: 0,
        regionName: '乌干达',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 32.290275,
        latitude: 1.373333,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7294,
        parentId: 0,
        regionName: '乌克兰',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 31.16558,
        latitude: 48.379433,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7295,
        parentId: 0,
        regionName: '安道尔',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 42.5,
        latitude: 1.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7296,
        parentId: 0,
        regionName: '阿拉伯联合酋长国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 24,
        latitude: 54,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7297,
        parentId: 0,
        regionName: '阿富汗',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 33,
        latitude: 65,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7298,
        parentId: 0,
        regionName: '安提瓜和巴布达',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 17.05,
        latitude: -61.8,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7299,
        parentId: 0,
        regionName: '安圭拉',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 18.25,
        latitude: -63.1667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7300,
        parentId: 0,
        regionName: '阿尔巴尼亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 41,
        latitude: 20,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7301,
        parentId: 0,
        regionName: '亚美尼亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 40,
        latitude: 45,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7302,
        parentId: 0,
        regionName: '荷属安地列斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 12.25,
        latitude: -68.75,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7303,
        parentId: 0,
        regionName: '安哥拉',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -12.5,
        latitude: 18.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7304,
        parentId: 0,
        regionName: '南极洲',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -90,
        latitude: 0,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7305,
        parentId: 0,
        regionName: '阿根廷',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -34,
        latitude: -64,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7306,
        parentId: 0,
        regionName: '美属萨摩亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -14.3333,
        latitude: -170,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7307,
        parentId: 0,
        regionName: '阿鲁巴',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 12.5,
        latitude: -69.9667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7308,
        parentId: 0,
        regionName: '阿塞拜疆',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 40.5,
        latitude: 47.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7309,
        parentId: 0,
        regionName: '波斯尼亚和黑塞哥维那',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 44,
        latitude: 18,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7310,
        parentId: 0,
        regionName: '巴巴多斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 13.1667,
        latitude: -59.5333,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7311,
        parentId: 0,
        regionName: '孟加拉',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 24,
        latitude: 90,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7312,
        parentId: 0,
        regionName: '比利时',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 50.8333,
        latitude: 4,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7313,
        parentId: 0,
        regionName: '布基纳法索',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 13,
        latitude: -2,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7314,
        parentId: 0,
        regionName: '保加利亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 43,
        latitude: 25,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7315,
        parentId: 0,
        regionName: '巴林',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 26,
        latitude: 50.55,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7316,
        parentId: 0,
        regionName: '布隆迪',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -3.5,
        latitude: 30,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7317,
        parentId: 0,
        regionName: '贝宁',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 9.5,
        latitude: 2.25,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7318,
        parentId: 0,
        regionName: '百慕大',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 32.3333,
        latitude: -64.75,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7319,
        parentId: 0,
        regionName: '文莱',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 4.5,
        latitude: 114.6667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7320,
        parentId: 0,
        regionName: '玻利维亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -17,
        latitude: -65,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7321,
        parentId: 0,
        regionName: '巴西',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -10,
        latitude: -55,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7322,
        parentId: 0,
        regionName: '巴哈马',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 24.25,
        latitude: -76,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7323,
        parentId: 0,
        regionName: '不丹',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 27.5,
        latitude: 90.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7324,
        parentId: 0,
        regionName: '布维岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -54.4333,
        latitude: 3.4,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7325,
        parentId: 0,
        regionName: '白俄罗斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 53,
        latitude: 28,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7326,
        parentId: 0,
        regionName: '伯利兹',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 17.25,
        latitude: -88.75,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7327,
        parentId: 0,
        regionName: '科科斯（基林）群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -12.5,
        latitude: 96.8333,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7328,
        parentId: 0,
        regionName: '刚果',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -1,
        latitude: 15,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7329,
        parentId: 0,
        regionName: '中非共和国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 7,
        latitude: 21,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7330,
        parentId: 0,
        regionName: '科特迪瓦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 8,
        latitude: -5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7331,
        parentId: 0,
        regionName: '库克群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -21.2333,
        latitude: -159.7667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7332,
        parentId: 0,
        regionName: '智利',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -30,
        latitude: -71,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7333,
        parentId: 0,
        regionName: '哥伦比亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 4,
        latitude: -72,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7334,
        parentId: 0,
        regionName: '哥斯达黎加',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 10,
        latitude: -84,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7335,
        parentId: 0,
        regionName: '古巴',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 21.5,
        latitude: -80,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7336,
        parentId: 0,
        regionName: '佛得角',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 16,
        latitude: -24,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7337,
        parentId: 0,
        regionName: '圣诞岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -10.5,
        latitude: 105.6667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7338,
        parentId: 0,
        regionName: '塞浦路斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 35,
        latitude: 33,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7339,
        parentId: 0,
        regionName: '捷克共和国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 49.75,
        latitude: 15.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7340,
        parentId: 0,
        regionName: '吉布提',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 11.5,
        latitude: 43,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7341,
        parentId: 0,
        regionName: '丹麦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 56,
        latitude: 10,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7342,
        parentId: 0,
        regionName: '多米尼克',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 15.4167,
        latitude: -61.3333,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7343,
        parentId: 0,
        regionName: '多米尼加共和国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 19,
        latitude: -70.6667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7344,
        parentId: 0,
        regionName: '阿尔及利亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 28,
        latitude: 3,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7345,
        parentId: 0,
        regionName: '厄瓜多尔',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -2,
        latitude: -77.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7346,
        parentId: 0,
        regionName: '爱沙尼亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 59,
        latitude: 26,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7347,
        parentId: 0,
        regionName: '埃及',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 27,
        latitude: 30,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7348,
        parentId: 0,
        regionName: '西撒哈拉',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 24.5,
        latitude: -13,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7349,
        parentId: 0,
        regionName: '厄立特里亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 15,
        latitude: 39,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7350,
        parentId: 0,
        regionName: '埃塞俄比亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 8,
        latitude: 38,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7351,
        parentId: 0,
        regionName: '斐济',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -18,
        latitude: 175,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7352,
        parentId: 0,
        regionName: '马尔维纳斯群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -51.75,
        latitude: -59,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7353,
        parentId: 0,
        regionName: '密克罗尼西亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 6.9167,
        latitude: 158.25,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7354,
        parentId: 0,
        regionName: '法罗群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 62,
        latitude: -7,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7355,
        parentId: 0,
        regionName: '加蓬',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -1,
        latitude: 11.75,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7356,
        parentId: 0,
        regionName: '格林纳达',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 12.1167,
        latitude: -61.6667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7357,
        parentId: 0,
        regionName: '格鲁吉亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 42,
        latitude: 43.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7358,
        parentId: 0,
        regionName: '法属圭亚那',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 4,
        latitude: -53,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7359,
        parentId: 0,
        regionName: '加纳',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 8,
        latitude: -2,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7360,
        parentId: 0,
        regionName: '直布罗陀',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 36.1833,
        latitude: -5.3667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7361,
        parentId: 0,
        regionName: '格陵兰岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 72,
        latitude: -40,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7362,
        parentId: 0,
        regionName: '冈比亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 13.4667,
        latitude: -16.5667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7363,
        parentId: 0,
        regionName: '几内亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 11,
        latitude: -10,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7364,
        parentId: 0,
        regionName: '瓜德罗普岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 16.25,
        latitude: -61.5833,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7365,
        parentId: 0,
        regionName: '赤道几内亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 2,
        latitude: 10,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7366,
        parentId: 0,
        regionName: '希腊',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 39,
        latitude: 22,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7367,
        parentId: 0,
        regionName: '南乔治亚岛和南桑威奇群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -54.5,
        latitude: -37,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7368,
        parentId: 0,
        regionName: '危地马拉',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 15.5,
        latitude: -90.25,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7369,
        parentId: 0,
        regionName: '关岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 13.4667,
        latitude: 144.7833,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7370,
        parentId: 0,
        regionName: '几内亚比绍',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 12,
        latitude: -15,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7371,
        parentId: 0,
        regionName: '圭亚那',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 5,
        latitude: -59,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7372,
        parentId: 0,
        regionName: '赫德岛和麦当劳群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -53.1,
        latitude: 72.5167,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7373,
        parentId: 0,
        regionName: '洪都拉斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 15,
        latitude: -86.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7374,
        parentId: 0,
        regionName: '克罗地亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 45.1667,
        latitude: 15.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7375,
        parentId: 0,
        regionName: '海地',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 19,
        latitude: -72.4167,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7376,
        parentId: 0,
        regionName: '匈牙利',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 47,
        latitude: 20,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7377,
        parentId: 0,
        regionName: '爱尔兰',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 53,
        latitude: -8,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7378,
        parentId: 0,
        regionName: '以色列',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 31.5,
        latitude: 34.75,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7379,
        parentId: 0,
        regionName: '英属印度洋领地',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -6,
        latitude: 71.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7380,
        parentId: 0,
        regionName: '伊拉克',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 33,
        latitude: 44,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7381,
        parentId: 0,
        regionName: '伊朗',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 32,
        latitude: 53,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7382,
        parentId: 0,
        regionName: '冰岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 65,
        latitude: -18,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7383,
        parentId: 0,
        regionName: '牙买加',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 18.25,
        latitude: -77.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7384,
        parentId: 0,
        regionName: '乔丹',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 31,
        latitude: 36,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7385,
        parentId: 0,
        regionName: '肯尼亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 1,
        latitude: 38,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7386,
        parentId: 0,
        regionName: '吉尔吉斯斯坦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 41,
        latitude: 75,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7387,
        parentId: 0,
        regionName: '柬埔寨',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 13,
        latitude: 105,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7388,
        parentId: 0,
        regionName: '基里巴斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 1.4167,
        latitude: 173,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7389,
        parentId: 0,
        regionName: '科摩罗',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -12.1667,
        latitude: 44.25,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7390,
        parentId: 0,
        regionName: '圣基茨和尼维斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 17.3333,
        latitude: -62.75,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7391,
        parentId: 0,
        regionName: '科威特',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 29.3375,
        latitude: 47.6581,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7392,
        parentId: 0,
        regionName: '开曼群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 19.5,
        latitude: -80.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7393,
        parentId: 0,
        regionName: '老挝',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 18,
        latitude: 105,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7394,
        parentId: 0,
        regionName: '黎巴嫩',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 33.8333,
        latitude: 35.8333,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7395,
        parentId: 0,
        regionName: '圣露西亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 13.8833,
        latitude: -61.1333,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7396,
        parentId: 0,
        regionName: '列支敦士登',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 47.1667,
        latitude: 9.5333,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7397,
        parentId: 0,
        regionName: '斯里兰卡',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 7,
        latitude: 81,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7398,
        parentId: 0,
        regionName: '利比里亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 6.5,
        latitude: -9.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7399,
        parentId: 0,
        regionName: '莱索托',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -29.5,
        latitude: 28.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7400,
        parentId: 0,
        regionName: '立陶宛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 56,
        latitude: 24,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7401,
        parentId: 0,
        regionName: '卢森堡',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 49.75,
        latitude: 6.1667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7402,
        parentId: 0,
        regionName: '拉脱维亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 57,
        latitude: 25,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7403,
        parentId: 0,
        regionName: '阿拉伯利比亚民众国',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 25,
        latitude: 17,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7404,
        parentId: 0,
        regionName: '摩洛哥',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 32,
        latitude: -5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7405,
        parentId: 0,
        regionName: '摩纳哥',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 43.7333,
        latitude: 7.4,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7406,
        parentId: 0,
        regionName: '摩尔多瓦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 47,
        latitude: 29,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7407,
        parentId: 0,
        regionName: '黑山',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 42,
        latitude: 19,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7408,
        parentId: 0,
        regionName: '马达加斯加',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -20,
        latitude: 47,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7409,
        parentId: 0,
        regionName: '马绍尔群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 9,
        latitude: 168,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7410,
        parentId: 0,
        regionName: '马其顿',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 41.8333,
        latitude: 22,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7411,
        parentId: 0,
        regionName: '马里',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 17,
        latitude: -4,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7412,
        parentId: 0,
        regionName: '缅甸',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 22,
        latitude: 98,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7413,
        parentId: 0,
        regionName: '蒙古',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 46,
        latitude: 105,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7414,
        parentId: 0,
        regionName: '北马里亚纳群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 15.2,
        latitude: 145.75,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7415,
        parentId: 0,
        regionName: '马提尼克岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 14.6667,
        latitude: -61,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7416,
        parentId: 0,
        regionName: '毛里塔尼亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 20,
        latitude: -12,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7417,
        parentId: 0,
        regionName: '蒙特塞拉特',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 16.75,
        latitude: -62.2,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7418,
        parentId: 0,
        regionName: '马耳他',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 35.8333,
        latitude: 14.5833,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7419,
        parentId: 0,
        regionName: '毛里求斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -20.2833,
        latitude: 57.55,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7420,
        parentId: 0,
        regionName: '马尔代夫',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 3.25,
        latitude: 73,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7421,
        parentId: 0,
        regionName: '马拉维',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -13.5,
        latitude: 34,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7422,
        parentId: 0,
        regionName: '墨西哥',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 23,
        latitude: -102,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7423,
        parentId: 0,
        regionName: '纳米比亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -22,
        latitude: 17,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7424,
        parentId: 0,
        regionName: '新喀里多尼亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -21.5,
        latitude: 165.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7425,
        parentId: 0,
        regionName: '尼日尔',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 16,
        latitude: 8,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7426,
        parentId: 0,
        regionName: '诺福克岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -29.0333,
        latitude: 167.95,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7427,
        parentId: 0,
        regionName: '尼日利亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 10,
        latitude: 8,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7428,
        parentId: 0,
        regionName: '尼加拉瓜',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 13,
        latitude: -85,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7429,
        parentId: 0,
        regionName: '挪威',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 62,
        latitude: 10,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7430,
        parentId: 0,
        regionName: '尼泊尔',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 28,
        latitude: 84,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7431,
        parentId: 0,
        regionName: '瑙鲁',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -0.5333,
        latitude: 166.9167,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7432,
        parentId: 0,
        regionName: '纽埃',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -19.0333,
        latitude: -169.8667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7433,
        parentId: 0,
        regionName: '阿曼',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 21,
        latitude: 57,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7434,
        parentId: 0,
        regionName: '巴拿马',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 9,
        latitude: -80,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7435,
        parentId: 0,
        regionName: '秘鲁',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -10,
        latitude: -76,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7436,
        parentId: 0,
        regionName: '法属波利尼西亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -15,
        latitude: -140,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7437,
        parentId: 0,
        regionName: '巴布亚新几内亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -6,
        latitude: 147,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7438,
        parentId: 0,
        regionName: '巴基斯坦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 30,
        latitude: 70,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7439,
        parentId: 0,
        regionName: '波兰',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 52,
        latitude: 20,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7440,
        parentId: 0,
        regionName: '圣皮埃尔和密克隆岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 46.8333,
        latitude: -56.3333,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7441,
        parentId: 0,
        regionName: '波多黎各',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 18.25,
        latitude: -66.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7442,
        parentId: 0,
        regionName: '葡萄牙',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 39.5,
        latitude: -8,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7443,
        parentId: 0,
        regionName: '帕劳',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 7.5,
        latitude: 134.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7444,
        parentId: 0,
        regionName: '巴拉圭',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -23,
        latitude: -58,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7445,
        parentId: 0,
        regionName: '卡塔尔',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 25.5,
        latitude: 51.25,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7446,
        parentId: 0,
        regionName: '留尼旺岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -21.1,
        latitude: 55.6,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7447,
        parentId: 0,
        regionName: '塞尔维亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 44,
        latitude: 21,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7448,
        parentId: 0,
        regionName: '卢旺达',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -2,
        latitude: 30,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7449,
        parentId: 0,
        regionName: '沙特阿拉伯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 25,
        latitude: 45,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7450,
        parentId: 0,
        regionName: '所罗门群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -8,
        latitude: 159,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7451,
        parentId: 0,
        regionName: '塞舌尔',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -4.5833,
        latitude: 55.6667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7452,
        parentId: 0,
        regionName: '苏丹',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 15,
        latitude: 30,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7453,
        parentId: 0,
        regionName: '瑞典',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 62,
        latitude: 15,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7454,
        parentId: 0,
        regionName: '斯洛文尼亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 46,
        latitude: 15,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7455,
        parentId: 0,
        regionName: '斯洛伐克',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 48.6667,
        latitude: 19.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7456,
        parentId: 0,
        regionName: '塞拉利昂',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 8.5,
        latitude: -11.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7457,
        parentId: 0,
        regionName: '圣马力诺',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 43.7667,
        latitude: 12.4167,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7458,
        parentId: 0,
        regionName: '塞内加尔',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 14,
        latitude: -14,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7459,
        parentId: 0,
        regionName: '索马里',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 10,
        latitude: 49,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7460,
        parentId: 0,
        regionName: '苏里南',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 4,
        latitude: -56,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7461,
        parentId: 0,
        regionName: '圣多美和普林西比',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 1,
        latitude: 7,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7462,
        parentId: 0,
        regionName: '萨尔瓦多',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 13.8333,
        latitude: -88.9167,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7463,
        parentId: 0,
        regionName: '叙利亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 35,
        latitude: 38,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7464,
        parentId: 0,
        regionName: '斯威士兰',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -26.5,
        latitude: 31.5,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7465,
        parentId: 0,
        regionName: '特克斯和凯科斯群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 21.75,
        latitude: -71.5833,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7466,
        parentId: 0,
        regionName: '乍得',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 15,
        latitude: 19,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7467,
        parentId: 0,
        regionName: '多哥',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 8,
        latitude: 1.1667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7468,
        parentId: 0,
        regionName: '塔吉克斯坦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 39,
        latitude: 71,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7469,
        parentId: 0,
        regionName: '托克劳',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -9,
        latitude: -172,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7470,
        parentId: 0,
        regionName: '土库曼斯坦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 40,
        latitude: 60,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7471,
        parentId: 0,
        regionName: '突尼斯',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 34,
        latitude: 9,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7472,
        parentId: 0,
        regionName: '汤加',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -20,
        latitude: -175,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7473,
        parentId: 0,
        regionName: '土耳其',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 39,
        latitude: 35,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7474,
        parentId: 0,
        regionName: '特立尼达和多巴哥',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 11,
        latitude: -61,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7475,
        parentId: 0,
        regionName: '图瓦卢',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -8,
        latitude: 178,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7476,
        parentId: 0,
        regionName: '坦桑尼亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -6,
        latitude: 35,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7477,
        parentId: 0,
        regionName: '乌拉圭',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -33,
        latitude: -56,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7478,
        parentId: 0,
        regionName: '乌兹别克斯坦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 41,
        latitude: 64,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7479,
        parentId: 0,
        regionName: null,
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 41.9,
        latitude: 12.45,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7480,
        parentId: 0,
        regionName: '委内瑞拉',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 8,
        latitude: -66,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7481,
        parentId: 0,
        regionName: '瓦努阿图',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -16,
        latitude: 167,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7482,
        parentId: 0,
        regionName: '瓦利斯和富图纳群岛',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -13.3,
        latitude: -176.2,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7483,
        parentId: 0,
        regionName: '萨摩亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -13.5833,
        latitude: -172.3333,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7484,
        parentId: 0,
        regionName: '也门',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: 15,
        latitude: 48,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7485,
        parentId: 0,
        regionName: '马约特',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -12.8333,
        latitude: 45.1667,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7486,
        parentId: 0,
        regionName: '南非',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -29,
        latitude: 24,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7487,
        parentId: 0,
        regionName: '赞比亚',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -15,
        latitude: 30,
        admincode: null,
        level: 0,
    },
    {
        regionId: 7488,
        parentId: 0,
        regionName: '津巴布韦',
        sort: 0,
        currency: null,
        timediff: null,
        longitude: -20,
        latitude: 30,
        admincode: null,
        level: 0,
    },
];
